AnnaDodson/step-challenge

StepChallenge.csproj
- So the front end build tasks are ran in the correct directory
=> Hard code the Client App build path

ClientApp/src/components/Login.js, ClientApp/src/components/Register.js, Startup.cs
- Add placeholder and disable submit button so user has to choose a team
- Update the password policy for auth
- Add link to register page on the login screen
=> Fixes and Improvements around Registering

ClientApp/src/App.js, ClientApp/src/components/Account.js, ClientApp/src/components/SettingsMenu.js
=> New account page

LICENSE
I've chosen this license to ensure the project is always open and users get the most benfit from the project
=> Create License and include in repo

ClientApp/src/components/Login.js, ClientApp/src/components/Register.js
- Added confirm password
- Changed name of login to email cos that's what people need to login in
with
=> Made registration page easier for people

ClientApp/package-lock.json, ClientApp/package.json
Also formatted the file properly
=> Added missing npm dependency for underscore

README.md, Startup.cs
- Added call to run the db migrations on startup of the app
- Updated README
- Fixes #29
=> Database is now created on startup of application

ClientApp/src/components/Register.js
=> Fixed registration validation errors

ClientApp/src/components/Account.js, ClientApp/src/components/UserSteps.js
- Changed You Steps to Your Steps
- Fixed broken GitHub links
=> Front end fixes

ClientApp/src/components/Account.js, ClientApp/src/components/CreateStepTable.js
- Refactored the create able function to display the date range  better
=> Show next week of steps from the Sunday onwards

ClientApp/src/components/Admin.js, Controllers/UserController.cs, DataModels/EditUserModel.cs, DataSeeder.cs, Model/GraphQL/UserType.cs, Services/ParticipantService.cs
- New field in the admin panel to select any user and make them an
admin or remove them as admin
- Added some more info to the user so you can see which team their in
and their username etc
=> Add allowing users to become admin roles

CONTRIBUTING.md, README.md
- To make it easier for contributions
=> Updated the README and CONTRIBUTING guide

StepChallenge/ClientApp/src/components/admin/adminScoreBoard.js, StepChallenge/ClientApp/src/components/admin/editParticipant.js, StepChallenge/ClientApp/src/components/admin/editTeams.js
- If a team name gets changed, the team in the list should also update
- Added list of participants to the edit team page
- Styling changes to make it nicer to the user
=> Fixed where drop downs weren't getting updated

StepChallenge/ClientApp/src/components/admin/editParticipant.js, StepChallenge/ClientApp/src/components/admin/editTeams.js
- Fixed the drop down not selecting correctly
=> Fixes for admin area

StepChallenge/ClientApp/src/components/Login.js, StepChallenge/Controllers/UserController.cs, StepChallenge/DataSeeder.cs, StepChallenge/Startup.cs
- Add better error respobse
- Add extra field into data seeder
=> Update locked out setting for login attempts

StepChallenge/Controllers/UserController.cs
- Because I accidentally set the lock out restrictions a bit
aggressively, added a check so that if an admin resets the password, the
lock out gets reset
=> Added check to remove locked out date if exists

CONTRIBUTING.md, README.md, StepChallenge/DataSeeder.cs, StepChallenge/Startup.cs
- Updated all the instructions to make it clearer for new contributors
- Updated the seeder to generate an admin user and documented it in the
README
=> Updated documentation and data seeder

StepChallenge/ClientApp/src/components/ScoreBoard.js, StepChallenge/ClientApp/src/components/admin/adminScoreBoard.js, StepChallenge/DataModels/LeaderBoard.cs, StepChallenge/Model/GraphQL/LeaderBoardType.cs, StepChallenge/Services/StepsService.cs
Added total steps to leaderboard and admin leaderboard. Total only includes steps from people and not steps given to teams with less people. Total is limited to last monday in the same way as the rest of the leaderboard
=> Added total steps to leaderboard

StepChallenge/ClientApp/src/App.css, StepChallenge/ClientApp/src/components/TeamStep.js
Added first letter of name as initial for easier viewing on team page
=> Added initials to team page

StepChallenge/ClientApp/src/components/TeamStep.js
Added a toUpperCase for the user initial so that they all match in the case that the users name starts with a lower case letter
=> Uppercased user initial

StepChallenge/ClientApp/src/components/Auth.js, StepChallenge/ClientApp/src/components/Register.js, StepChallenge/Controllers/RegisterController.cs
- Needed to update the register endpoint to return the session model
- Moved register api call into the auth js file so it's all consistent
and then it sets the cookies, not the register component
=> Fix for broken Register routing
